/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugPainelRouteImport } from './routes/$slug/painel'
import { Route as SlugQrcodesRouteImport } from './routes/$slug/qrcodes'
import { Route as SlugMesaNumeroRouteImport } from './routes/$slug/mesa/$numero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPainelRoute = SlugPainelRouteImport.update({
  id: '/$slug/painel',
  path: '/$slug/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugQrcodesRoute = SlugQrcodesRouteImport.update({
  id: '/$slug/qrcodes',
  path: '/$slug/qrcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugMesaNumeroRoute = SlugMesaNumeroRouteImport.update({
  id: '/$slug/mesa/$numero',
  path: '/$slug/mesa/$numero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/$slug/painel': typeof SlugPainelRoute
  '/$slug/qrcodes': typeof SlugQrcodesRoute
  '/$slug/mesa/$numero': typeof SlugMesaNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/$slug/painel': typeof SlugPainelRoute
  '/$slug/qrcodes': typeof SlugQrcodesRoute
  '/$slug/mesa/$numero': typeof SlugMesaNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/$slug/painel': typeof SlugPainelRoute
  '/$slug/qrcodes': typeof SlugQrcodesRoute
  '/$slug/mesa/$numero': typeof SlugMesaNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/$slug/painel' | '/$slug/qrcodes' | '/$slug/mesa/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/admin' | '/$slug/painel' | '/$slug/qrcodes' | '/$slug/mesa/$numero'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$slug/painel'
    | '/$slug/qrcodes'
    | '/$slug/mesa/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SlugPainelRoute: typeof SlugPainelRoute
  SlugQrcodesRoute: typeof SlugQrcodesRoute
  SlugMesaNumeroRoute: typeof SlugMesaNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/painel': {
      id: '/$slug/painel'
      path: '/$slug/painel'
      fullPath: '/$slug/painel'
      preLoaderRoute: typeof SlugPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/qrcodes': {
      id: '/$slug/qrcodes'
      path: '/$slug/qrcodes'
      fullPath: '/$slug/qrcodes'
      preLoaderRoute: typeof SlugQrcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/mesa/$numero': {
      id: '/$slug/mesa/$numero'
      path: '/$slug/mesa/$numero'
      fullPath: '/$slug/mesa/$numero'
      preLoaderRoute: typeof SlugMesaNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SlugPainelRoute: SlugPainelRoute,
  SlugQrcodesRoute: SlugQrcodesRoute,
  SlugMesaNumeroRoute: SlugMesaNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
