// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgjzegzlpxjiibpsgvge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnanplZ3pscHhqaWlicHNndmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg5MDE3MTUsImV4cCI6MjEwNDQ3NzcxNX0.DkgQnE4M3CsAQG7o2zkYxCiLf_8hI98v2oyukSN47xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});